classOrder = ["SignalService", "Signal", "Connection"]
changelog = true
gitSourceBranch = "main"

[docusaurus]
tagline = "A service that allows you to create custom events."

[home]
enabled = true
includeReadme = false