title = "SignalService"

classOrder = ["SignalService", "Signal", "Connection"]
changelog = true
gitSourceBranch = "main"

[docusaurus]
tagline = "A service that allows you to create custom events."
baseUrl = "/SignalService/"

[home]
enabled = true
includeReadme = false