[package]

name = "zxibs/signalservice"

realm = "shared"

description = "This module allows you to create custom events, see the documentation for more info: (documentation is not available yet.)"

registry = "https://github.com/UpliftGames/wally-index"

version = "0.2.1"

license = "MIT"

include = ["src"]

exclude = [
    ".vscode",
    "debug",
    "docs",
    "test",
    ".gitignore",
    ".styluaignore",
    "test.project.json",
    "default.project.json",
    "LICENSE.md",
    "README.md",
    "testez-companion.toml",
    "roblox.toml",
    "selene.toml",
    "stylua.toml",
    "wally.toml"
]