[package]
name = "osyrisrblx/t"
description = "A Runtime Typechecker for Roblox"
version = "3.0.0"
license = "MIT"
authors = ["Osyris"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
# include = ["lib", "default.project.json"]
exclude = ["node_modules", "package.json", "package-lock.json", "spec.lua", "lib/ts.lua", "lib/t.d.ts", "lib/init.spec.lua", "tsconfig.json", "rotriever.toml", "modules"]

[dependencies]
