name: CI

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint using Selene
        run: |
          selene src/

      - name: Format code using StyLua
        run: |
          stylua src/

      - name: Check for modified files in src
        id: git-check
        run: echo ::set-output name=modified::$(if git diff --quiet HEAD -- src; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions'
          git add src/
          git commit -m "Formatted code using StyLua"
          git push
