name: CI

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Lua 5.1
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "5.1"

      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install dependencies for testing
        run: luarocks install luafilesystem

      - name: Install required tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint using Selene
        run: |
          rm -f roblox.toml
          selene generate-roblox-std
          selene src/

      - name: Test using TestEZ
        run: |
          lua test/lemur.lua

      - name: Format code using StyLua
        run: |
          stylua src/

      - name: Check for modified files in src
        id: git-check
        run: echo ::set-output name=modified::$(if git diff --quiet HEAD -- src; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions'
          git add src/
          git commit -m "Formatted code using StyLua"
          git push
