name: CI

on: 
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build place file
        shell: bash
        run: |
          chmod +x test/build.bash
          ./test/build.bash

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        shell: bash
        run: |
          chmod +x test/run.bash
          ./test/run.bash

  code-quality:
    needs: tests
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install required tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint using Selene
        run: |
          selene src/

      - name: Format code using StyLua
        run: |
          stylua src/

      - name: Check for modified files inside src
        id: git-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git checkout "${GITHUB_REF:11}" --
          git add -AN
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD -- src; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions'
          git reset --soft HEAD
          git add src/
          git commit -m "Formatted code using StyLua"
          git push
