name: CI

on: 
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install LuaJIT
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "luajit"

      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install dependencies for testing
        run: luarocks install luafilesystem

      - name: Install required tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint using Selene
        run: |
          selene src/

      - name: Test using TestEZ
        shell: bash
        run: |
          DEPENDENCIES=$(awk '$0 == "[dependencies]" {i=1;next};i && i >= 0' wally.toml)
          cd test
          echo "$DEPENDENCIES" >> wally.toml
          wally install
          mkdir Packages || echo 'Packages already exists!'
          mkdir Packages/_Index || echo 'Packages/_Index already exists!'
          mkdir Packages/_Index/zxibs_signalservice
          cp -R ../src Packages/_Index/zxibs_signalservice/signalservice
          echo 'return require(script.Parent._Index["zxibs_signalservice"]["signalservice"])' > Packages/SignalService.lua
          cd ..
          lua test/lemur.lua

      - name: Format code using StyLua
        run: |
          stylua src/

      - name: Check for modified files inside src
        id: git-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git checkout "${GITHUB_REF:11}"
          git add -AN
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD -- src; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions'
          git reset --soft HEAD
          git add src/
          git commit -m "Formatted code using StyLua"
          git push
