name: Bump version and create changelog based on commits

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version for bumping ex: 1.0.0'
        required: true
        type: number

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repo history
        run: git fetch --prune --unshallow

      - name: Install required tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Bump version
        shell: bash
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          sed -i 's/.*version.*/version = '"\"$VERSION\""'/' wally.toml

      - name: Create changelog
        shell: bash
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          DATE=$(date +%F)
          git config --global alias.changelog "log --pretty=format:'- %s by @%an (%h)' --abbrev-commit"
          ADDED=$(git changelog --grep="ADDED:" $LAST_TAG..HEAD -- src/*.lua)
          CHANGED=$(git changelog --grep="CHANGED:" $LAST_TAG..HEAD -- src/*.lua)
          REMOVED=$(git changelog --grep="REMOVED:" $LAST_TAG..HEAD -- src/*.lua)
          FIXED=$(git changelog --grep="FIXED:" $LAST_TAG..HEAD -- src/*.lua)
          CHANGES="\n## v$VERSION - $DATE\n### Added\n\n$ADDED\n\n### Changed\n\n$CHANGED\n\n### Removed\n\n$REMOVED\n\n### Fixed\n\n$FIXED\n"
          echo '' > CHANGES.md
          awk 'NR==6 {$0="$CHANGES"} 1' CHANGES.md > changelog.md
          cat changelog.md

      - name: Create tag for release
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git config --global user.name 'github-actions'
          git tag -a -m "New release for v$VERSION" $VERSION

      - name: Push changes
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git add changelog.md wally.toml
          git commit -m "Bumped version to $VERSION and added a changelog for it"
          git push && git push --tags
