name: Lint and Format using Selene and StyLua

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint using Selene
        shell: bash
        run: |
          rm -f roblox.toml
          selene generate-roblox-std
          selene src/

      - name: Format code using StyLua
        run: |
          stylua src/

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        shell: bash
        run: |
          rm -rf .foreman-install
          git config --global user.name 'Github Actions'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -a -m "Formatted code using StyLua"
          git push