name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release to Wally
        shell: bash
        env:
          WALLY_AUTH: ${{ secrets.WALLY_AUTH }}
        run: |
          mkdir -p ~/.wally
          echo -e '[tokens]\n"https://api.wally.run/" = '"\"$WALLY_AUTH\"" > ~/.wally/auth.toml
          wally publish

      - name: Install SignalService
        shell: bash
        run: |
          cd publish
          wally install
          cd ..

      - name: Build place file
        run: |
          cd publish
          rojo build publish.project.json -o SignalService.rbxl
          cd ..

      - name: Create .rbxm file
        shell: bash
        run: |
          cd publish
          remodel run createRBXMFile.lua
          cd ..

      - name: Create .zip file
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r SignalService.zip publish/Packages
      
      - name: Publish release to github
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          body_path: publish/ReleaseNote.md
          files: |
              publish/SignalService.rbxm
              publish/SignalService.zip
